// Date: 8/29/2015 2:25:36 PM
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX

package com.dinodim.entitymodel;

import org.lwjgl.opengl.GL11;

import com.dinodim.entity.EntityDimetrodon;
import com.dinodim.main.DDUtils;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;
import net.minecraft.util.MathHelper;

public class ModelDimetrodon extends ModelBase
{
	//fields
    ModelRenderer head;
    ModelRenderer body;
    ModelRenderer leg1;
    ModelRenderer leg2;
    ModelRenderer leg3;
    ModelRenderer leg4;
    ModelRenderer tail;
    ModelRenderer sail;
  
  public ModelDimetrodon()
  {
    textureWidth = 64;
    textureHeight = 32;
    
      head = new ModelRenderer(this, 0, 0);
      head.addBox(-4F, -3F, -11F, 8, 5, 11);
      head.setRotationPoint(0F, 18F, -9F);
      head.setTextureSize(64, 32);
      head.mirror = true;
      DDUtils.setRotation(head, 0F, 0F, 0F);
      body = new ModelRenderer(this, 44, 6);
      body.addBox(-2F, -8F, -4F, 4, 20, 6);
      body.setRotationPoint(0F, 17F, -1F);
      body.setTextureSize(64, 32);
      body.mirror = true;
      DDUtils.setRotationDegrees(body, 90F, 0F, 0F);
      leg1 = new ModelRenderer(this, 28, 0);
      leg1.addBox(-3F, 0F, -2F, 4, 6, 4);
      leg1.setRotationPoint(-3F, 18F, 7F);
      leg1.setTextureSize(64, 32);
      leg1.mirror = true;
      DDUtils.setRotation(leg1, 0F, 0F, 0F);
      leg2 = new ModelRenderer(this, 28, 0);
      leg2.addBox(-1F, 0F, -2F, 4, 6, 4);
      leg2.setRotationPoint(3F, 18F, 7F);
      leg2.setTextureSize(64, 32);
      leg2.mirror = true;
      DDUtils.setRotation(leg2, 0F, 0F, 0F);
      leg2.mirror = true;
      leg3 = new ModelRenderer(this, 28, 0);
      leg3.addBox(-3F, 0F, -2F, 4, 6, 4);
      leg3.setRotationPoint(-3F, 18F, -5F);
      leg3.setTextureSize(64, 32);
      leg3.mirror = true;
      DDUtils.setRotation(leg3, 0F, 0F, 0F);
      leg3.mirror = false;
      leg4 = new ModelRenderer(this, 28, 0);
      leg4.addBox(-1F, 0F, -2F, 4, 6, 4);
      leg4.setRotationPoint(3F, 18F, -5F);
      leg4.setTextureSize(64, 32);
      leg4.mirror = true;
      DDUtils.setRotation(leg4, 0F, 0F, 0F);
      leg4.mirror = false;
      tail = new ModelRenderer(this, 0, 26);
      tail.addBox(0F, -1.5F, -1F, 15, 3, 3);
      tail.setRotationPoint(0F, 17F, 10F);
      tail.setTextureSize(64, 32);
      tail.mirror = true;
      DDUtils.setRotationDegrees(tail, 90F, -90F, 0F);
      sail = new ModelRenderer(this, 0, -2);
      sail.addBox(0F, -9F, -9F, 0, 9, 19);
      sail.setRotationPoint(0F, 15F, 0F);
      sail.setTextureSize(64, 32);
      sail.mirror = true;
      DDUtils.setRotation(sail, 0F, 0F, 0F);
  }
  
  /**
   * @param f parTime
   * @param f1 parSwingSuppress
   * @param f3 parHeadAngleY
   * @param f4 parHeadAngleX
   */
  @Override
  public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
	  this.renderCustom((EntityDimetrodon)entity, f, f1, f2, f3, f4, f5);
  }
  
  private void renderCustom(EntityDimetrodon entity, float f, float f1, float f2, float f3, float f4, float f5)
  {
	  super.render(entity, f, f1, f2, f3, f4, f5);
	  setRotationAngles(f, f1, f2, f3, f4, f5, entity);
	  
	  if (this.isChild)
      {
          float f6 = 2.0F;
          GL11.glPushMatrix();
          GL11.glScalef(1.0F / f6, 1.0F / f6, 1.0F / f6);
          GL11.glTranslatef(0.0F, 24.0F * f5, 0.0F);
          this.head.render(f5);
          this.body.render(f5);
          this.leg1.render(f5);
          this.leg2.render(f5);
          this.leg3.render(f5);
          this.leg4.render(f5);
          this.tail.render(f5);
    	  this.sail.render(f5);
          GL11.glPopMatrix();
      }
      else
      {
          this.head.render(f5);
          this.body.render(f5);
          this.leg1.render(f5);
          this.leg2.render(f5);
          this.leg3.render(f5);
          this.leg4.render(f5);
          this.tail.render(f5);
    	  this.sail.render(f5);
      }
  }
  
  @Override
  public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity e)
  {
	  super.setRotationAngles(f, f1, f2, f3, f4, f5, e);
	  this.leg1.rotateAngleX = MathHelper.cos(f * 0.4662F) * 2.4F * f1; //0.5662F was 0.6662F
      this.leg2.rotateAngleX = MathHelper.cos(f * 0.4662F + (float)Math.PI) * 2.4F * f1;
      this.leg3.rotateAngleX = MathHelper.cos(f * 0.4662F + (float)Math.PI) * 2.4F * f1;
      this.leg4.rotateAngleX = MathHelper.cos(f * 0.4662F) * 2.4F * f1; //2.4F was 1.4F for all
  }

}
