package com.dinodim.entitymodel;

import org.lwjgl.opengl.GL11;

import com.dinodim.entity.EntityTrilobite;
import com.dinodim.main.DDUtils;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

//Date: 9/7/2015 11:12:16 AM
//Template version 1.1
//Java generated by Techne
//Keep in mind that you still need to fill in some blanks
//- ZeuX
public class ModelTrilobite extends ModelBase
{
	//fields
	ModelRenderer head;
	ModelRenderer head2;
	ModelRenderer body1;
	ModelRenderer body2;
	ModelRenderer body3;
	ModelRenderer body4;
	ModelRenderer antenna1;
	ModelRenderer antenna1b;
	ModelRenderer antenna2;
	ModelRenderer antenna2b;
	static float rad90deg = DDUtils.degToRad(90F);


	public ModelTrilobite()
	{
		textureWidth = 32;
		textureHeight = 32;

		head = new ModelRenderer(this, 0, 3);
		head.addBox(-3F, -4F, 0F, 6, 3, 1);
		head.setRotationPoint(0F, 24F, 0F);
		head.setTextureSize(32, 32);
		head.mirror = true;
		DDUtils.setRotation(head, rad90deg, 0F, 0F);
		head2 = new ModelRenderer(this, 15, 0);
		head2.addBox(3F, 0F, 0F, 1, 1, 3);
		head2.addBox(-4F, 0F, 0F, 1, 1, 3);
		head2.setRotationPoint(0F, 23F, -3F);
		head2.setTextureSize(32, 32);
		head2.mirror = true;
		DDUtils.setRotation(head2, 0F, 0F, 0F);
		body1 = new ModelRenderer(this, 0, 8);
		body1.addBox(-2F, -2F, 0F, 4, 6, 2);
		body1.setRotationPoint(0F, 24F, -1F);
		body1.setTextureSize(32, 32);
		body1.mirror = true;
		DDUtils.setRotation(body1, rad90deg, 0F, 0F);
		body2 = new ModelRenderer(this, 14, 8);
		body2.addBox(-2F, 0F, 0F, 4, 1, 1);
		body2.setRotationPoint(0F, 24F, 3F);
		body2.setTextureSize(32, 32);
		body2.mirror = true;
		DDUtils.setRotation(body2, rad90deg, 0F, 0F);
		body3 = new ModelRenderer(this, 14, 11);
		body3.addBox(-1F, 0F, 0F, 2, 1, 1);
		body3.setRotationPoint(0F, 24F, 4F);
		body3.setTextureSize(32, 32);
		body3.mirror = true;
		DDUtils.setRotation(body3, rad90deg, 0F, 0F);
		body4 = new ModelRenderer(this, 14, 14);
		body4.addBox(-0.5F, 0F, 0F, 1, 1, 1);
		body4.setRotationPoint(0F, 24F, 5F);
		body4.setTextureSize(32, 32);
		body4.mirror = true;
		DDUtils.setRotation(body4, rad90deg, 0F, 0F);
		antenna1 = new ModelRenderer(this, 1, 1);
		antenna1.addBox(0F, 0F, -0.5F, 4, 0, 1);
		antenna1.setRotationPoint(1F, 23F, -3F);
		antenna1.setTextureSize(32, 32);
		antenna1.mirror = true;
		DDUtils.setRotation(antenna1, 0F, 1.134464F, 0F);
		antenna1b = new ModelRenderer(this, 0, 0);
		antenna1b.addBox(0.5F, 0F, -0.5F, 5, 0, 1);
		antenna1b.setRotationPoint(2F, 23F, -7F);
		antenna1b.setTextureSize(32, 32);
		antenna1b.mirror = true;
		DDUtils.setRotation(antenna1b, 0F, -0.7853982F, 0F);
		antenna2 = new ModelRenderer(this, 1, 1);
		antenna2.addBox(0F, 0F, -0.5F, 4, 0, 1);
		antenna2.setRotationPoint(-1F, 23F, -3F);
		antenna2.setTextureSize(32, 32);
		antenna2.mirror = true;
		DDUtils.setRotation(antenna2, 0F, 2.007129F, 0F);
		antenna2b = new ModelRenderer(this, 0, 0);
		antenna2b.addBox(0.5F, 0F, -0.5F, 5, 0, 1);
		antenna2b.setRotationPoint(-2F, 23F, -7F);
		antenna2b.setTextureSize(32, 32);
		antenna2b.mirror = true;
		DDUtils.setRotation(antenna2b, 0F, -2.356194F, 0F);
	}

	@Override
	public void render(Entity entity, float f, float f1, float f2, float f3, float f4, float f5)
	{
		super.render(entity, f, f1, f2, f3, f4, f5);
		setRotationAngles(f, f1, f2, f3, f4, f5, entity);
		if(this.isChild)
		{
			float f6 = 2.0F;
			GL11.glPushMatrix();
			GL11.glScalef(1.0F / f6, 1.0F / f6, 1.0F / f6);
			GL11.glTranslatef(0.0F, 24.0F * f5, 0.0F);
			head.render(f5);
			head2.render(f5);
			body1.render(f5);
			body2.render(f5);
			body3.render(f5);
			body4.render(f5);
			antenna1.render(f5);
			antenna2.render(f5);
			GL11.glPopMatrix();
		}
		else
		{
			head.render(f5);
			head2.render(f5);
			body1.render(f5);
			body2.render(f5);
			body3.render(f5);
			body4.render(f5);
			antenna1.render(f5);
			antenna1b.render(f5);
			antenna2.render(f5);
			antenna2b.render(f5);	
		}
	}

	@Override
	public void setRotationAngles(float f, float f1, float f2, float f3, float f4, float f5, Entity entity)
	{
		super.setRotationAngles(f, f1, f2, f3, f4, f5, entity);
	}

}

